#ifndef FITLOG_CONSTANTS_H
#define FITLOG_CONSTANTS_H

#define FITLOG_VERSION "0.1.0"
#define MAX_EXERCISE_NAME 64
#define MAX_NOTES 128

// Default configuration values
#define DEFAULT_DATE_FORMAT "YYYY-MM-DD"
#define DEFAULT_TIME_FORMAT "HH:MM"
#define DEFAULT_WEIGHT_UNIT "kg"
#define DEFAULT_DECIMAL_PLACES 1
#define DEFAULT_RECENT_COUNT 5

#endif